webtalk_init -webtalk_dir /home/mtayler/Documents/ceng441/cordic/cordic.sim/sim_board/behav/xsim/xsim.dir/board_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 30 14:29:04 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "647c7fef-b08c-4449-99b8-d63ffe5d1795" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "044bab3ca27a44d9b1053e8775472624" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "128" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2493.427 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "127528_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2143338240 -regid "" -xml /home/mtayler/Documents/ceng441/cordic/cordic.sim/sim_board/behav/xsim/xsim.dir/board_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mtayler/Documents/ceng441/cordic/cordic.sim/sim_board/behav/xsim/xsim.dir/board_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mtayler/Documents/ceng441/cordic/cordic.sim/sim_board/behav/xsim/xsim.dir/board_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
