# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache /var/log/xilinx//.Xil_mtayler/Vivado-79320-tayler-arch/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mtayler/Documents/ceng441/cordic/cordic.cache/wt [current_project]
set_property parent.project_path /home/mtayler/Documents/ceng441/cordic/cordic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths /opt/Digilent/vivado-boards/new/board_files [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/mtayler/Documents/ceng441/cordic/cordic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/theta_lookup.mem
read_verilog -library xil_defaultlib {
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/alu.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/controller.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/debouncer.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/dff_async_reset.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/regfile.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/cordic.v
  /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/new/board.v
}
read_vhdl -library xil_defaultlib /home/mtayler/Documents/ceng441/cordic/cordic.srcs/sources_1/imports/Downloads/hex_driver.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mtayler/Documents/ceng441/cordic/cordic.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/mtayler/Documents/ceng441/cordic/cordic.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc]


synth_design -top board -part xc7a35tcpg236-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_utilization_synth.rpt -pb board_utilization_synth.pb"
